var namespacemltk =
[
    [ "classifier", "namespacemltk_1_1classifier.html", "namespacemltk_1_1classifier" ],
    [ "clusterer", "namespacemltk_1_1clusterer.html", "namespacemltk_1_1clusterer" ],
    [ "datasets", "namespacemltk_1_1datasets.html", "namespacemltk_1_1datasets" ],
    [ "ensemble", null, [
      [ "AdaBoostClassifier", "classmltk_1_1ensemble_1_1AdaBoostClassifier.html", "classmltk_1_1ensemble_1_1AdaBoostClassifier" ],
      [ "AutoWeightedVoting", "classmltk_1_1ensemble_1_1AutoWeightedVoting.html", "classmltk_1_1ensemble_1_1AutoWeightedVoting" ],
      [ "BaggingClassifier", "classmltk_1_1ensemble_1_1BaggingClassifier.html", "classmltk_1_1ensemble_1_1BaggingClassifier" ],
      [ "Ensemble", "classmltk_1_1ensemble_1_1Ensemble.html", "classmltk_1_1ensemble_1_1Ensemble" ],
      [ "PerceptronCommittee", "classmltk_1_1ensemble_1_1PerceptronCommittee.html", "classmltk_1_1ensemble_1_1PerceptronCommittee" ],
      [ "VotingClassifier", "classmltk_1_1ensemble_1_1VotingClassifier.html", "classmltk_1_1ensemble_1_1VotingClassifier" ]
    ] ],
    [ "featselect", "namespacemltk_1_1featselect.html", "namespacemltk_1_1featselect" ],
    [ "metrics", null, [
      [ "dist", null, [
        [ "AdditiveSymmetric", "classmltk_1_1metrics_1_1dist_1_1AdditiveSymmetric.html", "classmltk_1_1metrics_1_1dist_1_1AdditiveSymmetric" ],
        [ "Average", "classmltk_1_1metrics_1_1dist_1_1Average.html", "classmltk_1_1metrics_1_1dist_1_1Average" ],
        [ "AverageL1Linf", "classmltk_1_1metrics_1_1dist_1_1AverageL1Linf.html", "classmltk_1_1metrics_1_1dist_1_1AverageL1Linf" ],
        [ "AvgManhattan", "classmltk_1_1metrics_1_1dist_1_1AvgManhattan.html", "classmltk_1_1metrics_1_1dist_1_1AvgManhattan" ],
        [ "Bhattacharyya", "classmltk_1_1metrics_1_1dist_1_1Bhattacharyya.html", "classmltk_1_1metrics_1_1dist_1_1Bhattacharyya" ],
        [ "Canberra", "classmltk_1_1metrics_1_1dist_1_1Canberra.html", "classmltk_1_1metrics_1_1dist_1_1Canberra" ],
        [ "Chebyshev", "classmltk_1_1metrics_1_1dist_1_1Chebyshev.html", "classmltk_1_1metrics_1_1dist_1_1Chebyshev" ],
        [ "Chord", "classmltk_1_1metrics_1_1dist_1_1Chord.html", "classmltk_1_1metrics_1_1dist_1_1Chord" ],
        [ "Clark", "classmltk_1_1metrics_1_1dist_1_1Clark.html", "classmltk_1_1metrics_1_1dist_1_1Clark" ],
        [ "Cosine", "classmltk_1_1metrics_1_1dist_1_1Cosine.html", "classmltk_1_1metrics_1_1dist_1_1Cosine" ],
        [ "Dice", "classmltk_1_1metrics_1_1dist_1_1Dice.html", "classmltk_1_1metrics_1_1dist_1_1Dice" ],
        [ "DistanceMetric", "classmltk_1_1metrics_1_1dist_1_1DistanceMetric.html", "classmltk_1_1metrics_1_1dist_1_1DistanceMetric" ],
        [ "Divergence", "classmltk_1_1metrics_1_1dist_1_1Divergence.html", "classmltk_1_1metrics_1_1dist_1_1Divergence" ],
        [ "Euclidean", "classmltk_1_1metrics_1_1dist_1_1Euclidean.html", "classmltk_1_1metrics_1_1dist_1_1Euclidean" ],
        [ "Hassanat", "classmltk_1_1metrics_1_1dist_1_1Hassanat.html", "classmltk_1_1metrics_1_1dist_1_1Hassanat" ],
        [ "Hellinger", "classmltk_1_1metrics_1_1dist_1_1Hellinger.html", "classmltk_1_1metrics_1_1dist_1_1Hellinger" ],
        [ "Jaccard", "classmltk_1_1metrics_1_1dist_1_1Jaccard.html", "classmltk_1_1metrics_1_1dist_1_1Jaccard" ],
        [ "Jeffreys", "classmltk_1_1metrics_1_1dist_1_1Jeffreys.html", "classmltk_1_1metrics_1_1dist_1_1Jeffreys" ],
        [ "JensenDifference", "classmltk_1_1metrics_1_1dist_1_1JensenDifference.html", "classmltk_1_1metrics_1_1dist_1_1JensenDifference" ],
        [ "JensenShannon", "classmltk_1_1metrics_1_1dist_1_1JensenShannon.html", "classmltk_1_1metrics_1_1dist_1_1JensenShannon" ],
        [ "KDivergence", "classmltk_1_1metrics_1_1dist_1_1KDivergence.html", "classmltk_1_1metrics_1_1dist_1_1KDivergence" ],
        [ "KullbackLeibler", "classmltk_1_1metrics_1_1dist_1_1KullbackLeibler.html", "classmltk_1_1metrics_1_1dist_1_1KullbackLeibler" ],
        [ "KumarJohnson", "classmltk_1_1metrics_1_1dist_1_1KumarJohnson.html", "classmltk_1_1metrics_1_1dist_1_1KumarJohnson" ],
        [ "Lorentzian", "classmltk_1_1metrics_1_1dist_1_1Lorentzian.html", "classmltk_1_1metrics_1_1dist_1_1Lorentzian" ],
        [ "Manhattan", "classmltk_1_1metrics_1_1dist_1_1Manhattan.html", "classmltk_1_1metrics_1_1dist_1_1Manhattan" ],
        [ "Matusita", "classmltk_1_1metrics_1_1dist_1_1Matusita.html", "classmltk_1_1metrics_1_1dist_1_1Matusita" ],
        [ "MaxSymmetric", "classmltk_1_1metrics_1_1dist_1_1MaxSymmetric.html", "classmltk_1_1metrics_1_1dist_1_1MaxSymmetric" ],
        [ "MinSymmetric", "classmltk_1_1metrics_1_1dist_1_1MinSymmetric.html", "classmltk_1_1metrics_1_1dist_1_1MinSymmetric" ],
        [ "Neyman", "classmltk_1_1metrics_1_1dist_1_1Neyman.html", "classmltk_1_1metrics_1_1dist_1_1Neyman" ],
        [ "NonIntersection", "classmltk_1_1metrics_1_1dist_1_1NonIntersection.html", "classmltk_1_1metrics_1_1dist_1_1NonIntersection" ],
        [ "Pearson", "classmltk_1_1metrics_1_1dist_1_1Pearson.html", "classmltk_1_1metrics_1_1dist_1_1Pearson" ],
        [ "ProbabilisticSymmetric", "classmltk_1_1metrics_1_1dist_1_1ProbabilisticSymmetric.html", "classmltk_1_1metrics_1_1dist_1_1ProbabilisticSymmetric" ],
        [ "Sorensen", "classmltk_1_1metrics_1_1dist_1_1Sorensen.html", "classmltk_1_1metrics_1_1dist_1_1Sorensen" ],
        [ "Squared", "classmltk_1_1metrics_1_1dist_1_1Squared.html", "classmltk_1_1metrics_1_1dist_1_1Squared" ],
        [ "SquaredChiSquared", "classmltk_1_1metrics_1_1dist_1_1SquaredChiSquared.html", "classmltk_1_1metrics_1_1dist_1_1SquaredChiSquared" ],
        [ "SquaredChord", "classmltk_1_1metrics_1_1dist_1_1SquaredChord.html", "classmltk_1_1metrics_1_1dist_1_1SquaredChord" ],
        [ "SquaredEuclidean", "classmltk_1_1metrics_1_1dist_1_1SquaredEuclidean.html", "classmltk_1_1metrics_1_1dist_1_1SquaredEuclidean" ],
        [ "Taneja", "classmltk_1_1metrics_1_1dist_1_1Taneja.html", "classmltk_1_1metrics_1_1dist_1_1Taneja" ],
        [ "Topsoe", "classmltk_1_1metrics_1_1dist_1_1Topsoe.html", "classmltk_1_1metrics_1_1dist_1_1Topsoe" ]
      ] ]
    ] ],
    [ "regressor", "namespacemltk_1_1regressor.html", "namespacemltk_1_1regressor" ],
    [ "validation", "namespacemltk_1_1validation.html", "namespacemltk_1_1validation" ],
    [ "visualize", "namespacemltk_1_1visualize.html", "namespacemltk_1_1visualize" ],
    [ "BorderlineSMOTEOne", "classmltk_1_1BorderlineSMOTEOne.html", "classmltk_1_1BorderlineSMOTEOne" ],
    [ "Data", "classmltk_1_1Data.html", "classmltk_1_1Data" ],
    [ "DSM", "classmltk_1_1DSM.html", "classmltk_1_1DSM" ],
    [ "Kernel", "classmltk_1_1Kernel.html", "classmltk_1_1Kernel" ],
    [ "Learner", "classmltk_1_1Learner.html", "classmltk_1_1Learner" ],
    [ "OverSampling", "classmltk_1_1OverSampling.html", "classmltk_1_1OverSampling" ],
    [ "Point", "classmltk_1_1Point.html", "classmltk_1_1Point" ],
    [ "RSM", "classmltk_1_1RSM.html", "classmltk_1_1RSM" ],
    [ "SMOTE", "classmltk_1_1SMOTE.html", "classmltk_1_1SMOTE" ],
    [ "Solution", "classmltk_1_1Solution.html", "classmltk_1_1Solution" ],
    [ "Statistics", "classmltk_1_1Statistics.html", null ],
    [ "Timer", "classmltk_1_1Timer.html", "classmltk_1_1Timer" ]
];