name: Meson

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install meson and dependencies
      run: |
            pip install meson
            sudo apt install gnuplot gnuplot-x11 ninja-build
    - name: Configure meson build
      run: meson . build
    - name: Compile project
      run: meson compile -C build
  macos-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install gnuplot
      run: brew install gnuplot meson
      
    - name: Configure meson build
      run: meson . build
    - name: Compile project
      run: meson compile -C build
      
  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install meson
      run: pip install meson ninja
      
    - name: Configure meson build
      run: meson . build --backend=vs
      
    - name: Compile project
      run: meson compile -C build
