name: Meson

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install meson and dependencies
      run: |
            pip install meson
            sudo apt install gnuplot gnuplot-x11 ninja-build
    - name: Configure meson build
      run: meson . build
    - name: Compile project
      run: meson compile -C build
